CREATE TABLE PRODUCT_STORAGE
(
	PRODUCT_ID 			VARCHAR2(15),
	PRODUCT_DATE 		DATE,
	STORAGE_CIY 		VARCHAR2(20),
	STORAGE_DISTRICT 	VARCHAR2(20),
	
	CONSTRAINT PS_prod_idDate_Sto_ctDis_pk
		PRIMARY KEY (PRODUCT_ID,PRODUCT_DATE,STORAGE_CIY,STORAGE_DISTRICT),
	CONSTRAINT PS_prod_id_date_fk
		FOREIGN KEY (PRODUCT_ID,PRODUCT_DATE)
		REFERENCES PRODUCT (PRODUCT_ID,PRODUCT_DATE),
	CONSTRAINT PS_sto_city_dist_fk
		FOREIGN KEY (STORAGE_CIY,STORAGE_DISTRICT)
		REFERENCES STORAGE (STORAGE_CIY,STORAGE_DISTRICT)
);


INSERT INTO PRODUCT_STORAGE VALUES ('PROD_0000001',TO_DATE('12-MAR-2019','DD-MON-YYYY'),'MIRPUR-2','DHAKA');
INSERT INTO PRODUCT_STORAGE VALUES ('PROD_0000002',TO_DATE('02-JAN-2019','DD-MON-YYYY'),'MIRPUR-12','DHAKA');
INSERT INTO PRODUCT_STORAGE VALUES ('PROD_0000003',TO_DATE('28-FEB-2019','DD-MON-YYYY'),'MOHAMMADPUR','DHAKA');
INSERT INTO PRODUCT_STORAGE VALUES ('PROD_0000004',TO_DATE('02-FEB-2019','DD-MON-YYYY'),'SHAHBAG','DHAKA');
INSERT INTO PRODUCT_STORAGE VALUES ('PROD_0000005',TO_DATE('12-JAN-2019','DD-MON-YYYY'),'MIRPUR-11','DHAKA');
