1. /* AGENT TRANSACTION */

SELECT AGENT_ID "AREA AGENT ID", TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE"
FROM AGENT_TRANSACTION; 


2. /* AGGREGATOR */ 

SELECT AGENT_ID "AREA AGENT ID", Collector_ID "WASTE COLLECTOR ID"
FROM AGGREGATOR;


3. /* AGENT TRANSPORTATION */

SELECT AGENT_ID "AREA AGENT ID", VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID"
FROM AGENT_TRANSPORTATION;


4. /* Area Agent */

SELECT agent_id "AREA AGENT ID", agent_name "NAME", agent_city "CITY", 
		agent_area "AREA", agent_shop_name "SHOP NAME",  agent_shop_open_time "SHOP OPENNING TIME",
		agent_shop_close_time "SHOP CLOSING TIME"
FROM Area_Agent;


5. /* Area_Agent_Contact_No */

SELECT agent_id "AREA AGENT ID", agent_name "NAME", agent_phone_no "CONTACT NO"
FROM Area_Agent_Contact_No JOIN Area_Agent USING (agent_id);



6. /* CLIENTS TRANSACTION */

SELECT CLIENT_TRADE_NUM "CLINET TRADE NO.", TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE"
FROM CLIENTS_TRANSACTION;



7. /* CLIENTS TRANSPORTATION */

SELECT CLIENT_TRADE_NUM "CLINET TRADE NO.",VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID"
FROM CLIENTS_TRANSPORTATION; 



8. /* CLIENTS */

SELECT CLIENT_TRADE_NUM "CLINET TRADE NO.", CLIENTS_COMPANY_NAME "COMPANY NAME"
FROM CLIENTS;



9. /* COLLECTOR */

SELECT AGENT_ID "AREA AGENT ID", dealer_dealership_no "DEALERSHIP NO."
FROM COLLECTOR;



10. /* COMPANY_TRANSACTION */ 

SELECT COMPANY_TRADE_NUM "COMPANY TRADE NO.", TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE"
FROM COMPANY_TRANSACTION;




11. /* COMPANY_TRANSPORTATION */

SELECT COMPANY_TRADE_NUM "COMPANY TRADE NO.", VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID"
FROM COMPANY_TRANSPORTATION;




12. /* COMPANY */

SELECT COMPANY_TRADE_NUM "COMPANY TRADE NO.", NAME, CONCAT(COLLECTION, ' kg') "COLLECTED WASTE", CONCAT(RECYCLED_AMOUNT, ' kg') "RECYCLED AMOUNT",
		CONCAT(EXPENSE, ' tk') "EXPENSE", CONCAT(CAST((RECYCLED_AMOUNT/COLLECTION)*100 AS DECIMAL(5,2)), '%') "PERCENTAGE OF RECYCLING"
FROM COMPANY;



13. /* DRIVER */

SELECT DRIVER_LICENSE_NUM "LICENSE NO.",  DRIVER_NAME "NAME", DRIVER_ADDRESS "ADDRESS", DRIVER_VEHICLE_TYPE "TYPE OF VEHICLE"
FROM DRIVER;



14. /* DRIVES */

SELECT VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID",DRIVER_LICENSE_NUM "DRIVER LICENSE NO."
FROM DRIVES;



15. /* Employee */

SELECT employee_id "EMPLOYEE ID", employee_name "NAME", employee_designation "DESIGNATION", CONCAT(employee_salary,' tk') "SALARY",
		employee_email "EMAIL", employee_phone_no "CONTACT NO."
FROM Employee JOIN Employee_Contact_No USING (employee_id);



16. /* ERROR */ 

SELECT process_id "PROCESS ID",process_date "DATE", error_type "ERROR TYPE", CONCAT(error_solving_cost,' tk') "SOLVING COST",
		employee_id "SUPERVISOR ID"
FROM Error;


17. /* LOCAL_DEALER_TRANSACTION */ 

SELECT dealer_dealership_no "DEALERSHIP NO.", TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE"
FROM LOCAL_DEALER_TRANSACTION;



18. /* LOCAL_DEALER_TRANSPORTATION */

SELECT dealer_dealership_no "DEALERSHIP NO.", VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID"
FROM LOCAL_DEALER_TRANSPORTATION; 



19. /* Local_Dealer */

SELECT dealer_dealership_no "DEALERSHIP NO.", dealer_name "NAME", dealer_city "CITY", dealer_district "DISTRICT"
FROM Local_Dealer;


20. /* Local_Waste_Collector */

SELECT Collector_ID "COLLECTOR ID", Collector_name "NAME", Collection_aera "AREA", Collector_type_of_waste "TYPE OF WASTE", CONCAT(Collector_waste_collected, ' kg') "COLLECTED AMOUNT",
		CONCAT(Collector_rate_of_waste,' tk') "PER UNIT PRICE",  CONCAT(Collector_income,' tk') "INCOME",  Collecting_Date "DATE", Collector_Contact_No "CONTACT NO."
FROM Local_Waste_Collector;

21. /* SCAVENGERS */

SELECT Collector_ID "COLLECTOR ID", Collector_name "NAME", Collection_aera "AREA", Collector_type_of_waste "TYPE OF WASTE",DUSTBIN_NUMBER "DUSTBIN NO.", CONCAT(Collector_waste_collected, ' kg') "COLLECTED AMOUNT", Collecting_Date "DATE",
		CONCAT(Collector_rate_of_waste,' tk') "PER UNIT PRICE", CONCAT(Collector_income,' tk') "INCOME", Collector_Contact_No "CONTACT NO."
FROM SCAVENGERS JOIN Local_Waste_Collector USING (Collector_ID);


22. /* WASTE_PICKER */

SELECT Collector_ID "COLLECTOR ID", Collector_name "NAME", Collection_aera "AREA", Collector_type_of_waste "TYPE OF WASTE", PICKING_HOUSE_NUMBER "HOUSE NO.", PICKING_ROAD_NUMBER "ROAD NO.",
		 Collector_waste_collected "COLLECTED AMOUNT", Collecting_Date "DATE", CONCAT(Collector_rate_of_waste,' tk') "PER UNIT PRICE",  CONCAT(Collector_income,' tk') "INCOME", Collector_Contact_No "CONTACT NO."
FROM WASTE_PICKER JOIN Local_Waste_Collector USING (Collector_ID);



22. /* INSTITUTION_WORKER */

SELECT Collector_ID "COLLECTOR ID", Collector_name "NAME", Collection_aera "AREA", Collector_type_of_waste "TYPE OF WASTE", INSTITUTION_NAME "INSTITUTION NAME", INSTITUTION_TYPE "INSTITUTION TYPE",
		Collector_waste_collected "COLLECTED AMOUNT", Collecting_Date "DATE", CONCAT(Collector_rate_of_waste,' tk') "PER UNIT PRICE",  CONCAT(Collector_income,' tk') "INCOME", Collector_Contact_No "CONTACT NO."
FROM INSTITUTION_WORKER JOIN Local_Waste_Collector USING (Collector_ID);



23. /* COMMUNITY_WORKER */

SELECT Collector_ID "COLLECTOR ID", Collector_name "NAME", Collection_aera "AREA", COMMUNITY_NAME "COMMUNITY NAME", COMMUNITY_HEAD "COMMUNITY HEAD NAME", COMMUNITY_HEAD_CONTACT_NUM "CONTACT NO.", COMMUNITY_WASTE_COLLECTOR_NUM "WASTE COLLECTOR NO.", 
		Collector_type_of_waste "TYPE OF WASTE", Collector_waste_collected "COLLECTED AMOUNT", Collecting_Date "DATE", CONCAT(Collector_rate_of_waste,' tk') "PER UNIT PRICE",  CONCAT(Collector_income,' tk') "INCOME", Collector_Contact_No "CONTACT NO."
FROM COMMUNITY_WORKER JOIN Local_Waste_Collector USING (Collector_ID);



24. /* PRODUCT_STORAGE */

SELECT PRODUCT_ID "PRODUCT ID", PRODUCT_DATE "PRODUCED DATE", STORAGE_CIY "STORAGE CIY", STORAGE_DISTRICT "STORAGE DISTRICT" 
FROM PRODUCT_STORAGE;



25. /* PRODUCT_TRANSACTION */

SELECT PRODUCT_ID "PRODUCT ID", PRODUCT_DATE "PRODUCED DATE", TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE"
FROM PRODUCT_TRANSACTION;



26. /* PRODUCT */

SELECT PRODUCT_ID "PRODUCT ID", PRODUCT_DATE "PRODUCED DATE", PRODUCT_NAME "NAME", 
		PRODUCT_TYPE "PRODUCT TYPE", EXPIRY_DATE "EXPIRY DATE", PRICE
FROM PRODUCT;


27. /* PRODUCTION */ 

SELECT COMPANY_TRADE_NUM "COMPANY TRADE NO.", PRODUCT_ID "PRODUCT ID", PRODUCT_DATE "PRODUCED DATE"
FROM PRODUCTION;



28. /* Recycling_Process */

SELECT process_id "PROCESS ID", process_date "PROCESSED DATE",CONCAT(process_collected_waste, ' kg') "COLLECTED WASTE",
		CONCAT(process_recycled_amount, ' kg') "RECYCLED AMOUNT",CONCAT(CAST((process_recycled_amount/process_collected_waste)*100 AS DECIMAL(20,2)), '%') "RECYCLING RATE"
FROM Recycling_Process;


29. /* STORAGE */

SELECT STORAGE_CIY "CITY", STORAGE_DISTRICT "DISTRICT", STORAGE_DATE "STORING DATE", AMOUNT_OF_STORE "STORING AMOUNT",
		 TOTAL_AMOUNT "TOTAL AMOUNT", TYPES_PRODUCT "TYPE OF PRODUCT"
FROM STORAGE;


30. /* TRANSACTION_SUPPORT */ 

SELECT TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE", TYPES_WASTE "WASTE TYPE", AMOUNT, PER_UNIT_PRICE "PRICE PER UNIT",
		TRANS_BUY_COMPANY "BUYING COMPANY", TRANS_SELL_COMPANY "SELLING DEALER"
FROM TRANSACTION_SUPPORT;



31. /* TRANSPORTATION */

SELECT VEHICLE_NUMBER "VEHICLE NO.", HIRER_ID "HIRER ID", VEHICLE_TYPE "TYPE OF VEHICLE", HIRER_ID "HIRER ID", SOURCE_TIME "STARTING TIME", SOURCE_DATE "DATE", 
		DESTINATION_TIME "ENDING TIME", DESTINATION_DATE "ENDING DATE", AVAILABILITY, PER_LOT_COST "HIRING COST"
FROM TRANSPORTATION;



32. /* WORKS */

SELECT COMPANY_TRADE_NUM "COMPANY TRADE NO.", EMPLOYEE_ID "EMPLOYEE ID"
FROM WORKS;