SELECT TRANSACTION_ID "TRANSACTION ID", TRANSACTION_DATE "TRANSACTION DATE", TYPES_WASTE "WASTE TYPE", AMOUNT, PER_UNIT_PRICE "PRICE PER UNIT",
		TRANS_BUY_COMPANY "BUYING COMPANY", TRANS_SELL_COMPANY "SELLING DEALER"
FROM TRANSACTION_SUPPORT 
WHERE TRANS_SELL_COMPANY IN (SELECT AGENT_ID FROM Area_Agent);

/* ALTERRING TABLE FOR ADDING COLUMN*/

ALTER TABLE Local_Waste_Collector ADD Collector_type VARCHAR2(20);

UPDATE Local_Waste_Collector SET Collector_type = 'SCAVENGERS' 
WHERE Collector_ID = 'COL_00000001' OR Collector_ID = 'COL_00000002';

UPDATE Local_Waste_Collector SET Collector_type = 'WASTE PICKER' 
WHERE Collector_ID = 'COL_00000003' OR Collector_ID = 'COL_00000004';

UPDATE Local_Waste_Collector SET Collector_type = 'INSTITUTION WORKER' 
WHERE Collector_ID = 'COL_00000005' OR Collector_ID = 'COL_00000006';

UPDATE Local_Waste_Collector SET Collector_type = 'COMMUNITY WORKER' 
WHERE Collector_ID = 'COL_00000007' OR Collector_ID = 'COL_00000008';



/* ALTERRING TABLE FOR ADDING COLUMN */

SELECT * FROM CLIENTS;

ALTER TABLE CLIENTS ADD CLIENTS_COMPANY_NAME VARCHAR2(50);

UPDATE CLIENTS SET CLIENTS_COMPANY_NAME = 'IMSAIL INDUSTRIES LTD.' 
WHERE CLIENT_TRADE_NUM = 'CLI_00000001';

UPDATE CLIENTS SET CLIENTS_COMPANY_NAME = 'PRAN INDUSTRIES LTD.' 
WHERE CLIENT_TRADE_NUM = 'CLI_00000002';

UPDATE CLIENTS SET CLIENTS_COMPANY_NAME = 'RASHID BRAVERAGE LTD.' 
WHERE CLIENT_TRADE_NUM = 'CLI_00000003';

UPDATE CLIENTS SET CLIENTS_COMPANY_NAME = 'RFL INDUSTRIES LTD.' 
WHERE CLIENT_TRADE_NUM = 'CLI_00000004';

UPDATE CLIENTS SET CLIENTS_COMPANY_NAME = 'MARLBORO ADVANCE COMPANY LTD.' 
WHERE CLIENT_TRADE_NUM = 'CLI_00000005';



/*ALTERRING TABLE FOR ADDING COLUMN COMPANY */
ALTER TABLE COMPANY ADD COMPANY_CITY VARCHAR2(50);
ALTER TABLE COMPANY ADD COMPANY_DISTRICT VARCHAR2(50);



UPDATE COMPANY SET COMPANY_CITY = 'MIRPUR 10',  COMPANY_DISTRICT = 'DHAKA'
WHERE COMPANY_TRADE_NUM = 'COMP_00000001';

UPDATE COMPANY SET COMPANY_CITY = 'MOHAMMADPUR',  COMPANY_DISTRICT = 'DHAKA'
WHERE COMPANY_TRADE_NUM = 'COMP_00000002';

UPDATE COMPANY SET COMPANY_CITY = 'MOHAKHALI',  COMPANY_DISTRICT = 'DHAKA'
WHERE COMPANY_TRADE_NUM = 'COMP_00000003';

UPDATE COMPANY SET COMPANY_CITY = 'BANANI',  COMPANY_DISTRICT = 'DHAKA'
WHERE COMPANY_TRADE_NUM = 'COMP_00000004';


UPDATE COMPANY SET COMPANY_CITY = 'GABTOLI',  COMPANY_DISTRICT = 'DHAKA'
WHERE COMPANY_TRADE_NUM = 'COMP_00000005';




/*ALTERRING TABLE FOR ADDING COLUMN COMPANY */
ALTER TABLE COMPANY ADD COMPANY_RECYCLE_TYPE VARCHAR2(15);



UPDATE COMPANY SET COMPANY_RECYCLE_TYPE = 'GLASS'
WHERE COMPANY_TRADE_NUM = 'COMP_00000001';
UPDATE COMPANY SET COMPANY_RECYCLE_TYPE = 'IRON'
WHERE COMPANY_TRADE_NUM = 'COMP_00000002';
UPDATE COMPANY SET COMPANY_RECYCLE_TYPE = 'PAPER'
WHERE COMPANY_TRADE_NUM = 'COMP_00000003';
UPDATE COMPANY SET COMPANY_RECYCLE_TYPE = 'PLASTIC'
WHERE COMPANY_TRADE_NUM = 'COMP_00000004';
UPDATE COMPANY SET COMPANY_RECYCLE_TYPE = 'TYRE'
WHERE COMPANY_TRADE_NUM = 'COMP_00000005';

