/* TRIGGER FOR VALID INSERT OR UPDATE OF DATA ON Recycling_Process */

CREATE OR REPLACE TRIGGER RECYLED_AMOUNT_TRIGGER
BEFORE INSERT OR UPDATE
ON Recycling_Process 

FOR EACH ROW 
WHEN (NEW.process_collected_waste < NEW.process_recycled_amount OR NEW.process_rate != CAST(((NEW.process_recycled_amount/NEW.process_collected_waste)*100) AS DECIMAL (10,2)))


DECLARE 
AMOUNT_LIMIT_EXCEED_ERROR EXCEPTION;
BEGIN
RAISE AMOUNT_LIMIT_EXCEED_ERROR;
EXCEPTION 
WHEN AMOUNT_LIMIT_EXCEED_ERROR
THEN 
	RAISE_APPLICATION_ERROR (-20343, 'IRRELEVANT DATA');
END;




/* TRIGGER */

CREATE OR REPLACE TRIGGER RECYLED_VALUE_TRIGGER
BEFORE INSERT 
ON Recycling_Process 

FOR EACH ROW 
WHEN (NEW.process_recycled_amount = NULL)

DECLARE 
AMOUNT_LIMIT_EXCEED_ERROR EXCEPTION;
BEGIN
RAISE AMOUNT_LIMIT_EXCEED_ERROR;
EXCEPTION 
WHEN AMOUNT_LIMIT_EXCEED_ERROR
THEN 
	RAISE_APPLICATION_ERROR (-20343, 'EMPTY DATA');
END;




