CREATE TABLE DRIVER
(
	DRIVER_LICENSE_NUM 		VARCHAR2(20),
	DRIVER_NAME  			VARCHAR2(20),
	DRIVER_ADDRESS		  	VARCHAR2(20),
	DRIVER_VEHICLE_TYPE 	VARCHAR2(20),
	   
	CONSTRAINT DRI_license_num_pk
		PRIMARY KEY (DRIVER_LICENSE_NUM)
);


INSERT INTO DRIVER VALUES ('DRV_LC_00000001','SADEKIN UDOY','MIRPUR DOHS','TRUCK');
INSERT INTO DRIVER VALUES ('DRV_LC_00000002','SHAHRIAR RIDOY','MOHAKHALI DOHS','MINI TRCUK');
INSERT INTO DRIVER VALUES ('DRV_LC_00000003','TAHSIN MAHMUD','KOLABAGAN','PICKUP');
INSERT INTO DRIVER VALUES ('DRV_LC_00000004','AAKIB UDDIN','MIRPUR 10','TRUCK');
INSERT INTO DRIVER VALUES ('DRV_LC_00000005','SHILAY RAHMAN','MIRPUR DOHS','VAN');
