CREATE TABLE  INSTITUTION_WORKER(
  COLLECTOR_ID  VARCHAR2(20),
  INSTITUTION_NAME VARCHAR2(40),
  INSTITUTION_TYPE VARCHAR2(20),

  CONSTRAINT LWC_IW_Collector_ID_pk_fk
  	PRIMARY KEY(Collector_ID),
  	FOREIGN KEY(Collector_ID)
  	REFERENCES  Local_Waste_Collector (Collector_ID)
  	ON DELETE CASCADE
);



INSERT INTO INSTITUTION_WORKER VALUES ('COL_00000005','MIST','UNIVERSITY');
INSERT INTO INSTITUTION_WORKER VALUES ('COL_00000006','KINGSTON HOSPITAL','HOSPITAL');
