CREATE TABLE  WASTE_PICKER(
  COLLECTOR_ID  VARCHAR2(20),
  PICKING_HOUSE_NUMBER NUMBER(20,5) CHECK (PICKING_HOUSE_NUMBER>0),
  PICKING_ROAD_NUMBER NUMBER(20,5) CHECK (PICKING_ROAD_NUMBER>0),
  
  CONSTRAINT LWC__WP_Collector_ID_pk
  	PRIMARY KEY(Collector_ID),
  	FOREIGN KEY(Collector_ID)
  	REFERENCES  Local_Waste_Collector (Collector_ID)
  	ON DELETE CASCADE
	
);


INSERT INTO WASTE_PICKER VALUES ('COL_00000003',10,120);
INSERT INTO WASTE_PICKER VALUES ('COL_00000004',9,20);
